//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActTask
    {
        public int id { get; set; }
        public string taskType { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime deadline { get; set; }
        public Nullable<int> repeatByTime { get; set; }
        public bool Reminder { get; set; }
        public string Description { get; set; }
        public int status { get; set; }
        public string creatorID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
    }
}
