//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal_product_chosenAttri
    {
        public int id { get; set; }
        public int deal_product_id { get; set; }
        public int optionID { get; set; }
        public Nullable<System.DateTime> addedDate { get; set; }
        public Nullable<System.DateTime> removeddate { get; set; }
        public bool active { get; set; }
    
        public virtual attributeOption attributeOption { get; set; }
        public virtual Deal_Product Deal_Product { get; set; }
    }
}
