//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal_Product()
        {
            this.deal_product_chosenAttri = new HashSet<deal_product_chosenAttri>();
        }
    
        public int id { get; set; }
        public int productID { get; set; }
        public int dealID { get; set; }
        public System.DateTime addedDate { get; set; }
        public Nullable<System.DateTime> removedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Deal Deal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deal_product_chosenAttri> deal_product_chosenAttri { get; set; }
        public virtual softwareProduct softwareProduct { get; set; }
    }
}
