//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.Deal_Product = new HashSet<Deal_Product>();
            this.Deal_SaleRep_Respon = new HashSet<Deal_SaleRep_Respon>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> Probability { get; set; }
        public string Creator { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompleteOn { get; set; }
        public int Client { get; set; }
        public Nullable<System.DateTime> LastUpdateStage { get; set; }
        public string Status { get; set; }
    
        public virtual contact contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_Product> Deal_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_SaleRep_Respon> Deal_SaleRep_Respon { get; set; }
    }
}
