//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSchedule_User
    {
        public int id { get; set; }
        public string userID { get; set; }
        public int scheduleID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MasterCalendar MasterCalendar { get; set; }
    }
}
