//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderItem()
        {
            this.orderItemOptions = new HashSet<orderItemOption>();
        }
    
        public int id { get; set; }
        public int productID { get; set; }
        public int orderID { get; set; }
        public double productPrice { get; set; }
        public Nullable<double> subOptionPrice { get; set; }
        public double totalprice { get; set; }
        public int productQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderItemOption> orderItemOptions { get; set; }
        public virtual order order { get; set; }
        public virtual softwareProduct softwareProduct { get; set; }
    }
}
