//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Step
    {
        public int id { get; set; }
        public int planID { get; set; }
        public Nullable<int> previousStep { get; set; }
        public Nullable<int> nextStep { get; set; }
        public int stepNo { get; set; }
        public string StepEmailContent { get; set; }
    
        public virtual PrePurchase_FollowUp_Plan PrePurchase_FollowUp_Plan { get; set; }
    }
}
